#Site settings
title: Aziz Khilawala
description: Aspiring UX Designer and Full Stack Developer
email: khilawalaaziz@gmail.com


# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
